name: test pipelite
run-name: ${{ github.actor }} run test
on: [push]
jobs:
  Introduse-Task:
    runs-on: ubuntu
    steps:
      - run: echo "Repository name: ${{ github.repository }}"
      - run: echo "Runner os: ${{ runner.os }}"
      - run: echo "Event name: : ${{ github.event_name }}"
  Checkout-Task:
    runs-on: windows
      steps:
        -run: echo " Chekout "
        -name: Check out code
          uses: actions/checkout@v4
        - run: echo "Repo ${{ girhub.repository }} is cloned
        - run: echo " Runner os: ${{ runner.os}}
        - run: dir ${{ github.workspace }}
        
      
